name: "Check"
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/determinate-nix-action@v3
      - uses: DeterminateSystems/magic-nix-cache-action@v9
      - name: Run check script
        run: ./scripts/check.sh
        env:
          DOTFILES_USERNAME: runner
          DOTFILES_HOME: /home/runner
          DOTFILES_DIRECTORY: ${{ github.workspace }}
